[project]
name = "arnold"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "wandb>=0.24.2",
]

[dependency-groups]
dev = [
    "ipdb>=0.13",
    "ipython>=8.0",
]

[tool.setuptools.packages.find]
include = ["renewed_tasks*", "renewed_utils*"]
